# This is a basic workflow to help you get started with Actions

# Name of the workflow
name: Learn GitHub Actions
# Name of the workflow run
run-name: Learn GitHub Actions!
# Controls when the workflow will run
on: [ push ]
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #  push:
  #    branches: [ "aprendiendo-github-actions" ]
  # pull_request:
  # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
# workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "hello-world"
  hello-world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      # Define a variable and print it
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Mostrar variable
        run: |
          echo $USERNAME
          echo $GITHUB_ENV
      # Setup Node.js environment and install dependencies
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          # Set always-auth in npmrc.
          always-auth: false
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 20.14.0
      - name: Verify node and npm versions
        run: |
          node --version
          npm --version
          ls -la
      - name: Install dependencies
        run: npm install
      - name: Verify installed dependencies
        run: ls -la
      - name: Run main.ts
        run: npx ts-node main.ts
      - name: Run hello_world.py
        run: python hello_world.py
