# This is a basic workflow to help you get started with Actions
# triggers.yml => executes when a workflow is triggered

name: Learn GitHub Actions (trigger)
run-name: Learn GitHub Actions! (trigger)
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - 'warning'
          - 'error'
          - 'debug'
      tags:
        description: 'Tags'
        required: false
        type: boolean
      environment:
        description: 'Environment'
        required: true
        type: environment
  push:
    branches:
      - aprendiendo-github-actions
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**.py'
  issue_comment:
    types:
      - created
  schedule:
    - cron: '30 5,17 * * *'
jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir nombre
        run: echo "USERNAME=${{ inputs.logLevel }}" >> $GITHUB_ENV
      - name: Definir lenguaje
        run: echo "LANGUAGE=${{ inputs.tags }}" >> $GITHUB_ENV
      - name: Correr script
        run: python hello_language.py
  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python hello_world.py
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}